### ISSUE TITLE
Problem: Need a way to check schema change PR's for valid json

### ISSUE THREAD

**Issue by jhsimpson** [JiscRDSS/rdss-par#5]
Contributors can check their proposed schema changes manually before submitting Pull Requests.  It would  be better for Pull Requests to be automatically checked against a json linter.

**Comment by sevein** [comment]
@carlwilson I've submitted a pull request (#7) to add the validator requested in #6. As part of that task I worked on a commit that adds integration with Travis but I haven't included it in my pull request because this issue is assigned to you. This is what I put together: https://github.com/JiscRDSS/rdss-par/commit/55ae3421b3bc392e17028be49ab7e0a01a74adb3 - it's not included in my pull request #7.
